---

sudo: required

language: python
python: 2.7

services:
  - docker

install:
  - pip install -r test-requirements.txt

script:
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
